# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ext_foo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import foo_pb2 as foo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ext_foo.proto',
  package='foo.ext_foo',
  syntax='proto2',
  serialized_pb=_b('\n\rext_foo.proto\x12\x0b\x66oo.ext_foo\x1a\tfoo.proto*D\n\x03WOD\x12\x07\n\x03Sun\x10\x00\x12\x07\n\x03Mon\x10\x01\x12\x07\n\x03Tue\x10\x02\x12\x07\n\x03Wed\x10\x03\x12\x07\n\x03Thu\x10\x04\x12\x07\n\x03\x46ri\x10\x05\x12\x07\n\x03Sat\x10\x06:\x17\n\x04name\x12\t.foo.Body\x18\x01 \x01(\t:\x15\n\x02id\x12\t.foo.Body\x18\x02 \x01(\r:(\n\x03wod\x12\t.foo.Body\x18\x03 \x01(\x0e\x32\x10.foo.ext_foo.WOD')
  ,
  dependencies=[foo__pb2.DESCRIPTOR,])

_WOD = _descriptor.EnumDescriptor(
  name='WOD',
  full_name='foo.ext_foo.WOD',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Sun', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Mon', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Tue', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Wed', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Thu', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Fri', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Sat', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=41,
  serialized_end=109,
)
_sym_db.RegisterEnumDescriptor(_WOD)

WOD = enum_type_wrapper.EnumTypeWrapper(_WOD)
Sun = 0
Mon = 1
Tue = 2
Wed = 3
Thu = 4
Fri = 5
Sat = 6

NAME_FIELD_NUMBER = 1
name = _descriptor.FieldDescriptor(
  name='name', full_name='foo.ext_foo.name', index=0,
  number=1, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None, file=DESCRIPTOR)
ID_FIELD_NUMBER = 2
id = _descriptor.FieldDescriptor(
  name='id', full_name='foo.ext_foo.id', index=1,
  number=2, type=13, cpp_type=3, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None, file=DESCRIPTOR)
WOD_FIELD_NUMBER = 3
wod = _descriptor.FieldDescriptor(
  name='wod', full_name='foo.ext_foo.wod', index=2,
  number=3, type=14, cpp_type=8, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None, file=DESCRIPTOR)

DESCRIPTOR.enum_types_by_name['WOD'] = _WOD
DESCRIPTOR.extensions_by_name['name'] = name
DESCRIPTOR.extensions_by_name['id'] = id
DESCRIPTOR.extensions_by_name['wod'] = wod
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

foo__pb2.Body.RegisterExtension(name)
foo__pb2.Body.RegisterExtension(id)
wod.enum_type = _WOD
foo__pb2.Body.RegisterExtension(wod)

# @@protoc_insertion_point(module_scope)
