# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='foo.proto',
  package='foo',
  syntax='proto2',
  serialized_pb=_b('\n\tfoo.proto\x12\x03\x66oo\"?\n\x07Message\x12\x1b\n\x06header\x18\x01 \x02(\x0b\x32\x0b.foo.Header\x12\x17\n\x04\x62ody\x18\x02 \x02(\x0b\x32\t.foo.Body\"\x16\n\x06Header\x12\x0c\n\x04type\x18\x01 \x02(\r\"\x10\n\x04\x42ody*\x08\x08\x01\x10\x80\x80\x80\x80\x02')
)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='foo.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='foo.Message.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='foo.Message.body', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=81,
)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='foo.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='foo.Header.type', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=105,
)


_BODY = _descriptor.Descriptor(
  name='Body',
  full_name='foo.Body',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(1, 536870912), ],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=123,
)

_MESSAGE.fields_by_name['header'].message_type = _HEADER
_MESSAGE.fields_by_name['body'].message_type = _BODY
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Body'] = _BODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'foo_pb2'
  # @@protoc_insertion_point(class_scope:foo.Message)
  ))
_sym_db.RegisterMessage(Message)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
  DESCRIPTOR = _HEADER,
  __module__ = 'foo_pb2'
  # @@protoc_insertion_point(class_scope:foo.Header)
  ))
_sym_db.RegisterMessage(Header)

Body = _reflection.GeneratedProtocolMessageType('Body', (_message.Message,), dict(
  DESCRIPTOR = _BODY,
  __module__ = 'foo_pb2'
  # @@protoc_insertion_point(class_scope:foo.Body)
  ))
_sym_db.RegisterMessage(Body)


# @@protoc_insertion_point(module_scope)
