// Code generated by protoc-gen-go.
// source: ext.proto
// DO NOT EDIT!

/*
Package ext is a generated protocol buffer package.

It is generated from these files:
	ext.proto

It has these top-level messages:
	EchoRequest
	EchoResponse
	FooRequest
	FooResponse
*/
package ext

import proto "gitlab.ucloudadmin.com/udb/uframework/message/protobuf/proto"
import fmt "fmt"
import math "math"
import foo "proto_foo/proto/foo"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type MessageType int32

const (
	MessageType_ECHO_REQUEST    MessageType = 100
	MessageType_ECHO_RESPONSE   MessageType = 101
	MessageType_FOO1_REQUEST    MessageType = 102
	MessageType_FOO1_RESPONSE   MessageType = 103
	MessageType_FOO2_REQUEST    MessageType = 104
	MessageType_FOO2_RESPONSE   MessageType = 105
	MessageType_SIMPLE_RESPONSE MessageType = 999
)

var MessageType_name = map[int32]string{
	100: "ECHO_REQUEST",
	101: "ECHO_RESPONSE",
	102: "FOO1_REQUEST",
	103: "FOO1_RESPONSE",
	104: "FOO2_REQUEST",
	105: "FOO2_RESPONSE",
	999: "SIMPLE_RESPONSE",
}
var MessageType_value = map[string]int32{
	"ECHO_REQUEST":    100,
	"ECHO_RESPONSE":   101,
	"FOO1_REQUEST":    102,
	"FOO1_RESPONSE":   103,
	"FOO2_REQUEST":    104,
	"FOO2_RESPONSE":   105,
	"SIMPLE_RESPONSE": 999,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EchoRequest struct {
	Msg              *string `protobuf:"bytes,1,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EchoRequest) Reset()                    { *m = EchoRequest{} }
func (m *EchoRequest) String() string            { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()               {}
func (*EchoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EchoRequest) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type EchoResponse struct {
	Msg              *string `protobuf:"bytes,1,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EchoResponse) Reset()                    { *m = EchoResponse{} }
func (m *EchoResponse) String() string            { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()               {}
func (*EchoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EchoResponse) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type FooRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FooRequest) Reset()                    { *m = FooRequest{} }
func (m *FooRequest) String() string            { return proto.CompactTextString(m) }
func (*FooRequest) ProtoMessage()               {}
func (*FooRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type FooResponse struct {
	Rc               *foo.Rc `protobuf:"bytes,1,req,name=rc" json:"rc,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FooResponse) Reset()                    { *m = FooResponse{} }
func (m *FooResponse) String() string            { return proto.CompactTextString(m) }
func (*FooResponse) ProtoMessage()               {}
func (*FooResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FooResponse) GetRc() *foo.Rc {
	if m != nil {
		return m.Rc
	}
	return nil
}

var E_EchoRequest = &proto.ExtensionDesc{
	ExtendedType:  (*foo.Body)(nil),
	ExtensionType: (*EchoRequest)(nil),
	Field:         100,
	Name:          "foo.ext.echo_request",
	Tag:           "bytes,100,opt,name=echo_request,json=echoRequest",
}

var E_EchoResponse = &proto.ExtensionDesc{
	ExtendedType:  (*foo.Body)(nil),
	ExtensionType: (*EchoResponse)(nil),
	Field:         101,
	Name:          "foo.ext.echo_response",
	Tag:           "bytes,101,opt,name=echo_response,json=echoResponse",
}

var E_Foo1Request = &proto.ExtensionDesc{
	ExtendedType:  (*foo.Body)(nil),
	ExtensionType: (*FooRequest)(nil),
	Field:         102,
	Name:          "foo.ext.foo1_request",
	Tag:           "bytes,102,opt,name=foo1_request,json=foo1Request",
}

var E_Foo1Response = &proto.ExtensionDesc{
	ExtendedType:  (*foo.Body)(nil),
	ExtensionType: (*FooResponse)(nil),
	Field:         103,
	Name:          "foo.ext.foo1_response",
	Tag:           "bytes,103,opt,name=foo1_response,json=foo1Response",
}

var E_Foo2Request = &proto.ExtensionDesc{
	ExtendedType:  (*foo.Body)(nil),
	ExtensionType: (*FooRequest)(nil),
	Field:         104,
	Name:          "foo.ext.foo2_request",
	Tag:           "bytes,104,opt,name=foo2_request,json=foo2Request",
}

var E_Foo2Response = &proto.ExtensionDesc{
	ExtendedType:  (*foo.Body)(nil),
	ExtensionType: (*FooResponse)(nil),
	Field:         105,
	Name:          "foo.ext.foo2_response",
	Tag:           "bytes,105,opt,name=foo2_response,json=foo2Response",
}

var E_SimpleResponse = &proto.ExtensionDesc{
	ExtendedType:  (*foo.Body)(nil),
	ExtensionType: (*foo.SimpleResponse)(nil),
	Field:         999,
	Name:          "foo.ext.simple_response",
	Tag:           "bytes,999,opt,name=simple_response,json=simpleResponse",
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "foo.ext.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "foo.ext.EchoResponse")
	proto.RegisterType((*FooRequest)(nil), "foo.ext.FooRequest")
	proto.RegisterType((*FooResponse)(nil), "foo.ext.FooResponse")
	proto.RegisterEnum("foo.ext.MessageType", MessageType_name, MessageType_value)
	proto.RegisterExtension(E_EchoRequest)
	proto.RegisterExtension(E_EchoResponse)
	proto.RegisterExtension(E_Foo1Request)
	proto.RegisterExtension(E_Foo1Response)
	proto.RegisterExtension(E_Foo2Request)
	proto.RegisterExtension(E_Foo2Response)
	proto.RegisterExtension(E_SimpleResponse)
}

var fileDescriptor0 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4f, 0xc2, 0x30,
	0x14, 0xc0, 0x03, 0x1e, 0x96, 0xbd, 0x16, 0xc1, 0x89, 0x91, 0x78, 0x91, 0x70, 0x30, 0xc4, 0xc3,
	0x12, 0x7a, 0xe4, 0x26, 0x5a, 0x82, 0x89, 0x38, 0xec, 0xf0, 0x4c, 0xcc, 0xe8, 0x36, 0x12, 0xb1,
	0x73, 0x9d, 0x09, 0x7c, 0x0d, 0xbf, 0x24, 0x5f, 0xc3, 0xac, 0x94, 0xfd, 0xc1, 0x45, 0x6f, 0x7d,
	0x2f, 0x3f, 0x7e, 0xfc, 0x78, 0x80, 0xc9, 0x37, 0x89, 0x1d, 0xc5, 0x22, 0x11, 0x96, 0xe1, 0x0b,
	0x61, 0xf3, 0x4d, 0x72, 0x65, 0xa6, 0x0f, 0xb5, 0xeb, 0x5d, 0x03, 0xa2, 0x5e, 0x28, 0x18, 0xff,
	0xfc, 0xe2, 0x32, 0xb1, 0x5a, 0x70, 0xb2, 0x96, 0x41, 0xa7, 0xd6, 0xad, 0xf7, 0x4d, 0x96, 0x3e,
	0x7b, 0x5d, 0xc0, 0x7b, 0x40, 0x46, 0xe2, 0x43, 0xf2, 0x0a, 0x02, 0x03, 0x8c, 0xc5, 0xc1, 0xd0,
	0xbb, 0x01, 0xa4, 0x26, 0x8d, 0x5f, 0x42, 0x3d, 0xf6, 0x14, 0x8d, 0x88, 0x61, 0xa7, 0xdf, 0xcb,
	0x3c, 0x56, 0x8f, 0xbd, 0xdb, 0xef, 0x1a, 0xa0, 0x29, 0x97, 0xf2, 0x2d, 0xe0, 0xf3, 0x6d, 0x94,
	0x7a, 0x31, 0xbd, 0x9f, 0x38, 0x0b, 0x46, 0x5f, 0x5e, 0xa9, 0x3b, 0x6f, 0x2d, 0xad, 0x33, 0x68,
	0xe8, 0x8d, 0x3b, 0x73, 0x9e, 0x5d, 0xda, 0x52, 0xd0, 0xd8, 0x71, 0x06, 0x19, 0xe4, 0xa7, 0x90,
	0xde, 0x68, 0x28, 0xd0, 0x10, 0xc9, 0xa0, 0x50, 0x43, 0x24, 0x87, 0x56, 0x56, 0x1b, 0x9a, 0xee,
	0xe3, 0x74, 0xf6, 0x44, 0xf3, 0xe5, 0xce, 0x18, 0x8e, 0x00, 0x73, 0x2f, 0x14, 0x8b, 0x58, 0x9f,
	0xc3, 0x54, 0xc5, 0x23, 0xb1, 0xdc, 0x76, 0x96, 0xdd, 0x5a, 0x1f, 0x91, 0xb6, 0xad, 0x6f, 0x68,
	0x17, 0xae, 0xc6, 0x10, 0xcf, 0x87, 0x21, 0x85, 0x86, 0x76, 0xe8, 0x13, 0x14, 0x24, 0x5c, 0x49,
	0x2e, 0x8e, 0x24, 0x7b, 0x8e, 0x61, 0x5e, 0x98, 0x86, 0x77, 0x80, 0x7d, 0x21, 0x06, 0x55, 0x29,
	0xbe, 0xb2, 0x9c, 0x67, 0x96, 0xfc, 0xfa, 0x0c, 0xa5, 0x9f, 0x39, 0x94, 0x3c, 0x40, 0x43, 0x2b,
	0x7e, 0x97, 0x04, 0x47, 0x3f, 0xa7, 0xf0, 0x9f, 0x31, 0xbc, 0x97, 0x94, 0x42, 0x48, 0x55, 0x48,
	0xf8, 0x77, 0x08, 0x29, 0x87, 0x90, 0xca, 0x90, 0xd5, 0x3f, 0x21, 0x24, 0x0b, 0x99, 0x40, 0x53,
	0xae, 0xd6, 0xd1, 0x3b, 0xaf, 0xf4, 0xec, 0x8c, 0x42, 0x8c, 0xab, 0xb8, 0xcc, 0x73, 0x2a, 0x4b,
	0xf3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x55, 0x98, 0x81, 0xa1, 0x14, 0x03, 0x00, 0x00,
}
